### ISSUE TITLE
Questions about the a detail in the NAACL '21 paper.

### ISSUE THREAD

**Issue by guanqun-yang** [GU-DataLab/stance-detection-KE-MLM#3]
Thank you for the NAACL '21 paper. It provides an interesting way to incorporate knowledge in fine-tuning BERT. The experimental result is also comprehensive and persuasive. 

But I have a question about the fine-tuning process

- In Eqn 5, it seems to me that both $y_i$ and $\hat{y}_i$ with dimension equal to the vocabulary size. This makes output of the model a vector rather than a scalar. Then how do you compute gradient in this setting?
- If multiple words are masked in the same sentence (see below). Then how do you decide the output of the second masked token when the first masked token is already predicted (for example [MASK] -> hilarious) ? Do you use the new token (hilarious) or you still stick to the original token (happy)? 
> ORIGINAL: I'm so happy Biden beat Trump in the debate
> MASKED: I'm so [MASK] Biden [MASK] Trump in the debate.

**Comment by kornosk** [comment]
@guanqun-yang  Thank you for your interest! This project is a very long time ago but I will try to answer your questions.

1. I believe I intend to make `$y_i$ log $\hat{y}_i$` means `$y_i$ dot product with log $\hat{y}_i$`. So the final loss is a scalar.
2. I stick with the original token, otherwise, the prediction of the next tokens would be very off the way. We wouldn't want the later tokens to be dependent on the previous tokens.
